---
version: 2
multicolumn: false
web-width: '800'
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/8850/articles/172750/master/file/figures/1.5_Kipp1/1.5_Kipp1.png"
    path: figures/1.5_Kipp1/1.5_Kipp1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
